// Copyright 2024 QMK -- generated source code only, image retains original copyright
// SPDX-License-Identifier: GPL-2.0-or-later

// This file was auto-generated by `qmk painter-convert-graphics --input /home/harvey/Github/skb_qmk_userspace/temp_font_stuff/7.png --output /home/harvey/Github/skb_qmk_userspace/temp_font_stuff --format mono2 --no-rle False --no-deltas False`

#pragma once

#include <qp.h>

extern const uint32_t gfx_7_length;
extern const uint8_t  gfx_7[650];
