MOUSEKEY_ENABLE = yes
EXTRAKEY_ENABLE = yes
AUTO_SHIFT_ENABLE = no
TAP_DANCE_ENABLE = no
CAPS_WORD_ENABLE = yes
KEY_OVERRIDE_ENABLE = no
SPI_DRIVER_REQUIRED = yes
CUSTOM_MATRIX = lite

# Myriad boilerplate
SRC += myriad.c matrix.c chordmap.c encoder.c
ANALOG_DRIVER_REQUIRED = yes
POINTING_DEVICE_DRIVER = custom

